fix 04_fix_testcode
runteq/rspec_app_exam pull request #12
Opened 2021-03-21 10:04 UTC by Kagem1tsu

FIXME:
it 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること'
=> 'view Todos'が別ウィンドウで開いているので、検証するウィンドウを直近で開いたウィンドウにて行う様修正。

it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること'
=>日時の表記が違っていたので、アプリ側のコードに合わせて修正。

it 'Taskが削除されること'
=>ページのタイトルをカウントしていると思ったので、scopeを調整。

TODO:
各所letを用いてリファクタリング
`it 'Taskが削除されること' do`のみletで置き換えると

`1) Task Task削除 正常系 Taskが削除されること
     Failure/Error: click_link 'Destroy'
     
     Capybara::ElementNotFound:
       Unable to find link "Destroy"`
のエラーが出てしまったので、置き換えていません。

traitを使ってのリファクタリング
spec/factories/task.rb内にtraitを追記

2021-03-22 03:08 UTC, yuji91 requested changes
修正が問題ないかどうかは、テスト実行時のスクリーンショットがあると分かりやすいですね！

また指摘事項の修正はコミットの単位を分けるようにお願いします。

コミットメッセージについては、以下のURLを参考にしてください。
https://www.tam-tam.co.jp/tipsnote/program/post16686.html

2021-03-22 03:08 UTC, yuji91 commented on spec/factories/tasks.rb
> +      status { 'done' }
`String`ではなく`Symbol`で記載した方が`enum`の値であることが伝わりますね！
```suggestion
      status { :done }
```

2021-03-22 03:08 UTC, yuji91 commented on spec/support/driver_setting.rb
> +    # driven_by(:selenium_chrome_headless)
コミットするときは戻しておいた方が良いと思います！（コード差分に表示する必要がないので）

2021-03-22 03:08 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task)    { create(:task, project_id: project.id) }
Factoryに`association`をつけると`project_id`を記載しなくて済みますね。
```suggestion
  let(:task)    { create(:task) }
```

2021-03-22 03:08 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :complete, project_id: project.id )
コメント消しておいた方が良いかと思います！

2021-03-22 12:31 UTC, Kagem1tsu commented on spec/factories/tasks.rb
> +      status { 'done' }
5db8eb2354b1cbc71581bc4d80bc53e2fd5b7d07 表記方法を`symbol`へ修正しました。

2021-03-22 12:40 UTC, Kagem1tsu commented on spec/support/driver_setting.rb
> +    # driven_by(:selenium_chrome_headless)
1f5ca73213f092d0f8739b4a87c5abb068113332 `:selenium_chrome_headless`に戻しました。
直接レビューに関係しない部分はコード差分出さない方がいいということ理解しました。commitしなくても良かったということですよね？

2021-03-22 12:56 UTC, Kagem1tsu commented on spec/system/task_spec.rb
> +  let(:task)    { create(:task, project_id: project.id) }
2821bf1bb7d91e16ee1c8c395f701de96a974729 `factory`に`association`を追加し、`spec/system/task_spec.rb`をリファクタリングしました。
併せて`pending`が出ていた、`spec/models/task_spec.rb`にて`pending`がでないようコメントアウトしました。

2021-03-22 13:00 UTC, Kagem1tsu commented on spec/system/task_spec.rb
> +        task = create(:task, :complete, project_id: project.id )
840ec4edb5e397acb5d67c56dc86b8b98d2a2616 コメント消しました。

2021-03-22 13:03 UTC, Kagem1tsu commented
![](https://gyazo.com/219b6374da49c987e7d0c8731dc0ec1a.png)
以上、修正しspecの実行成功しました。

2021-03-26 07:24 UTC, yuji91 commented on spec/support/driver_setting.rb
> +    # driven_by(:selenium_chrome_headless)
はい、ここはコミットしなくて大丈夫です！

2021-03-26 07:25 UTC, yuji91 approved these changes
修正問題ないです！

ですがマージ対象のリポジトリが間違っているので、こちらでクローズさせて頂きます！

2021-03-26 07:25 UTC, closed without merging