[Modify] Fix testcode
runteq/rspec_app_exam pull request #15
Opened 2021-03-23 11:56 UTC by H-hidetaka

pull requestを間違えてしまったので再度修正
８つを修正
・it '一覧ページにアクセスした場合、Taskが表示されること' doをリファクタリング
・it 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること' do　コード追加
・it 'Taskが新規作成されること' do　リファクタリング(let)
・it 'Taskが表示されること' do リファクタリング
・it 'Taskを編集した場合、一覧画面で編集後の内容が表示されること' do　リファクタリング
・it 'ステータスを完了にした場合、Taskの完了日に今日の日付が登録されること' do　リファクタリング
・it '既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと' do
　trait使用
・it 'Taskが削除されること' do　コード修正

2021-03-23 12:38 UTC, yuji91 requested changes
指摘事項については、それぞれ修正のコミットの単位を分けるように対応をお願いします。

またファイル差分を確認したところ、意図したと思えない変更があったのでこちら問題ないかどうかご確認ください。
https://github.com/runteq/rspec_app_exam/pull/15/files

![image](https://user-images.githubusercontent.com/28836274/112147326-eba0f080-8c1f-11eb-9e95-b1b78a16ce3c.png)

2021-03-23 12:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task)
`let!`を使うことであらかじめテストデータを用意することができます。
現場でもよく使われる記法なので、試してみてください。

2021-03-23 12:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        click_link 'Show Todo'
こちらの修正は何が原因、問題でどのように修正したのかについての説明は可能でしょうか？

2021-03-23 12:39 UTC, yuji91 commented
テストを実行した結果、問題ないかどうかのスクリーンショットも添付頂くとレビューしやすいのでお願いします！

2021-03-23 13:08 UTC, H-hidetaka commented on spec/system/task_spec.rb
> +        click_link 'Show Todo'
原因・問題　
it 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること' do
とあったので、まず最初に詳細ページに飛ぶ必要があると判断しました。
その為、詳細ページへのパスとリンクがないことが問題だと思い、
リンク、パスを追加することで修正としました。

2021-03-23 13:19 UTC, H-hidetaka commented
[![Image from Gyazo](https://i.gyazo.com/b6c97965ed5c0f111dbb39f49d26ca9a.jpg)](https://gyazo.com/b6c97965ed5c0f111dbb39f49d26ca9a)

2021-03-24 03:05 UTC, yuji91 commented
これってテスト成功してますか？

2021-03-24 07:49 UTC, H-hidetaka commented
[![Image from Gyazo](https://i.gyazo.com/a8c5a2f9b5fdeac93d71c450bea214f8.jpg)](https://gyazo.com/a8c5a2f9b5fdeac93d71c450bea214f8)

2021-03-24 08:15 UTC, yuji91 requested changes
細かい点１点だけ対応をお願いします！

2021-03-24 08:15 UTC, yuji91 commented on spec/system/task_spec.rb
> +        done = create(:task, :done)
ここも`let!`で記載してみましょうか。
また`done`という変数名では分かりづらいので`task_done`くらいの名前が良いかと思います。

2021-03-24 08:17 UTC, H-hidetaka commented on spec/system/task_spec.rb
> +        done = create(:task, :done)
承知しました！

2021-03-24 08:28 UTC, H-hidetaka commented
[![Image from Gyazo](https://i.gyazo.com/c4f2d45c4ffb8591801f94efbf15325c.png)](https://gyazo.com/c4f2d45c4ffb8591801f94efbf15325c)

2021-03-24 08:30 UTC, yuji91 commented on spec/system/task_spec.rb
> +        done = create(:task, :done)
17bc936 のようにコミットIDを半角で記載するとリンクになるので、レビューの指摘事項を対応した際はリンク形式で対応箇所を伝えた方が良いので覚えておいてくださいm(_ _)m

2021-03-24 08:39 UTC, yuji91 approved these changes
LGTMです！

ですが`マージ対象のリポジトリが間違っている`ので、このPRはマージせずにクローズします。※マージすると課題が直ってしまい、他の人が学習することができなくなってしまうためです。

本来はPRを改めて作り直して頂きたいのですが、自分も気づくのが遅かったのと、修正は完了しているのでこの課題はこれで完了でOKです。応用編に進んでください。

またバグの修正自体は問題ないですが、レビュー依頼時に内容の確認が出来ていないことが何度かありました。自分が課題要件に記載した注意点は確認されていますか？

現場では成果物のレビューを依頼する前に問題がないかを必ず確認するようにしてください。
確認する内容をチェックリスト化して、作業時に漏れないようにすることをお薦めします。

2021-03-24 08:39 UTC, closed without merging

2021-03-24 08:44 UTC, H-hidetaka commented
「レビュー依頼時に内容の確認が出来ていないことが何度かありました。自分が課題要件に記載した注意点は確認されていますか？
現場では成果物のレビューを依頼する前に問題がないかを必ず確認するようにしてください。
確認する内容をチェックリスト化して、作業時に漏れないようにすることをお薦めします。」

この部分があまり意識できてなかったので、これから意識していくようにします！
ありがとうございました！